name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Unit Tests
      run: make test

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.9.0
        args: --timeout=5m

    # make sure we can build the cli
    - name: Build
      run: |
        make build
